   apiVersion: apps/v1
     kind: Deployment
     metadata:
       name: devopers-project
     spec:
       replicas: 3
       selector:
         matchLabels:
           app: devops-app
       template:
         metadata:
           labels:
             app: devops-app
         spec:
           containers:
           - name: devops-app
             image: amirulxhafiz/devopsproject:latest
             ports:
             - containerPort: 3000