 apiVersion: v1
     kind: Service
     metadata:
       name: devopers-project
     spec:
       type: LoadBalancer
       ports:
       - port: 80
         targetPort: 3000
       selector:
         app: devops-app
